name: Scala build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  # Run scalatest
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: 17
          - os: ubuntu-latest
            java: 21
          - os: ubuntu-latest
            java: 24
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
        cache: sbt

    - name: Setup SBT
      uses: sbt/setup-sbt@v1

    - name: Build and test
      shell: bash
      run: sbt -v +test test-serial:test

  test-assembly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: sbt

      - name: Setup SBT
        uses: sbt/setup-sbt@v1

      - name: Build assembly
        shell: bash
        run: |
          sbt -v assembly
          mv target/scala-*/jelly-cli-assembly*.jar jelly-cli.jar

      - name: Test the assembly
        run: |
          java -jar jelly-cli.jar version && \
          echo '_:b <http://t.org/> _:b .' | java -jar jelly-cli.jar \
            rdf to-jelly --in-format=nt > out.jelly && \
            [ -s out.jelly ]
